apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zpyr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-zpyr@sha256:9c28a73b8d614790ec1243029998b73f2a0985bf98e45d2d5058af5866c24c39
        name: my-nodejs
        resources: {}
status: {}
